env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
plugins:
  - jest
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
