version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Unit tests
          command: npm run test
      - run:
          name: Lint
          command: npm run lint
